course app/Models/course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace course_app.Models
{
    public class course
    {
        public int id { get; set; }
        public string name { get; set; }
    }
}

course app/Models/instructor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace course_app.Models
{
    public class instructor
    {

        public int id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string surname { get; set; }
        [Required]
        public string gender { get; set; }
            [Required]
        public int age { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string password { get; set; }

        public byte[] image { get; set; }
        [Required]
        public string field { get; set; }
        public int section_id { get; set; }
        public int student_id { get; set; }
        public double midterm { get; set; }
        public double final { get; set; }
        
    }
}

course app/Models/parent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace course_app.Models
{
    public class parent
    {
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string surname { get; set; }
        [Required]
        public string gender { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string password { get; set; }
        [Required]
        public int age { get; set; }

        public byte[] image { get; set; }
        
        public int student_id { get; set; }
    }
    
}

course app/Models/registrar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace course_app.Models
{
    public class registrar
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public int age { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public byte[] image { get; set; }
        public int section_id { get; set; }
    }
}

course app/Models/student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace course_app.Models
{
    public class student
    {
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string surname { get; set; }
        [Required]
        public string gender { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string password { get; set; }
      
        public byte[] image{ get; set; }
        [Required]
        public int age { get; set; }
        public int section_id { get; set; }

    }
}

course app/Models/student_list.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace course_app.Models
{
    public class student_list
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public string student_surname { get; set; }
        public List<student_main_page> student_s { get; set; }
        public double midterm { get; set; }
        public double final { get; set; }
        public string course_name { get; set; }
        public int section_id { get; set; }
        public string section_date { get; set; }
    }
}

course app/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using course_app.Models;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;
using course_app.Helpers;
namespace course_app.Controllers
{
    public class CourseController : Controller
    {

        MySqlConnection conn = new MySqlConnection("database= course; datasource = localhost; port = 3306; username = root; password =0000;");
        // GET: Course
        [HttpPost]
        public ActionResult Index(string button)
        {
            return View("Login");

        }
        public ActionResult Index()
        {
            temp = null;
            temp1=null;
            temporary = null;
            Session.Remove("ActiveUser");
            Session.Clear();
            return View();


        }

        [HttpPost]
        public ActionResult Login(login a)
        {
            List<string> user = new List<string>();
            string str = "";
            conn.Open();
            MySqlCommand cmd = new MySqlCommand($"select email,title from login where email='{a.email}' and password='{a.password}';", conn);

            MySqlDataReader MyReader;
            MyReader = cmd.ExecuteReader();
            while (MyReader.Read())
            {
                Console.WriteLine(MyReader["title"].ToString());
                str = MyReader["title"].ToString();
            }

            conn.Close();
            if (String.IsNullOrEmpty(str))
                return View("error");
            else if (str == "student")
            {
                Session.Add("ActiveUser", str);
                conn.Open();
                MySqlCommand cmd2 = new MySqlCommand($"select * from student where email='{a.email}' and password='{a.password}';", conn);

                MyReader = cmd2.ExecuteReader();
                while (MyReader.Read())
                {
                    //Console.WriteLine(MyReader["title"].ToString());
                    user.Add(MyReader["id"].ToString());
                    user.Add(MyReader["name"].ToString());
                    user.Add(MyReader["surname"].ToString());
                    user.Add(MyReader["gender"].ToString());
                    user.Add(MyReader["age"].ToString());
                    user.Add(MyReader["email"].ToString());
                    user.Add(MyReader["password"].ToString());
                }

                conn.Close();
                var _courseHelper = new CourseHelper();
                var student = _courseHelper.student(Convert.ToInt32(user[0]));
                student.name = user[1];
                student.surname = user[2];
                student.gender = user[3];
                student.age = Convert.ToInt32(user[4]);
                student.email = user[5];
                student.password = user[6];
                return RedirectToAction("student", student);
                //  return View(student);

            }
            else if (str == "instructor")
            {
                Session.Add("ActiveUser", str);
                conn.Open();
                MySqlCommand cmd2 = new MySqlCommand($"select * from instructor where email='{a.email}' and password='{a.password}';", conn);

                MyReader = cmd2.ExecuteReader();
                while (MyReader.Read())
                {
                    //Console.WriteLine(MyReader["title"].ToString());
                    user.Add(MyReader["id"].ToString());
                    user.Add(MyReader["name"].ToString());
                    user.Add(MyReader["surname"].ToString());
                    user.Add(MyReader["gender"].ToString());
                    user.Add(MyReader["age"].ToString());
                    user.Add(MyReader["email"].ToString());
                    user.Add(MyReader["password"].ToString());
                    user.Add(MyReader["field"].ToString());
                }

                conn.Close();
                instructor instructor = new instructor();
                instructor.id = Convert.ToInt32(user[0]);
                instructor.name = user[1];
                instructor.surname = user[2];
                instructor.gender = user[3];
                instructor.age = Convert.ToInt32(user[4]);
                instructor.email = user[5];
                instructor.password = user[6];
                instructor.field = user[7];
                return RedirectToAction("instructor", instructor);
            }
            else if (str == "registrar")
            {
                Session.Add("ActiveUser", str);
                conn.Open();
                MySqlCommand cmd2 = new MySqlCommand($"select * from registrar where email='{a.email}' and password='{a.password}';", conn);

                MyReader = cmd2.ExecuteReader();
                while (MyReader.Read())
                {
                    //Console.WriteLine(MyReader["title"].ToString());
                    user.Add(MyReader["id"].ToString());
                    user.Add(MyReader["name"].ToString());
                    user.Add(MyReader["surname"].ToString());
                    user.Add(MyReader["gender"].ToString());
                    user.Add(MyReader["age"].ToString());
                    user.Add(MyReader["email"].ToString());
                    user.Add(MyReader["password"].ToString());

                }

                conn.Close();
                registrar registrar = new registrar();
                registrar.id = Convert.ToInt32(user[0]);
                registrar.name = user[1];
                registrar.surname = user[2];
                registrar.gender = user[3];
                registrar.age = Convert.ToInt32(user[4]);
                registrar.email = user[5];
                registrar.password = user[6];

                return RedirectToAction("registrar", registrar);
            }


            else
            {
                Session.Add("ActiveUser", str);
                conn.Open();
                MySqlCommand cmd2 = new MySqlCommand($"select * from parent where email='{a.email}' and password='{a.password}';", conn);

                MyReader = cmd2.ExecuteReader();
                while (MyReader.Read())
                {
                    //Console.WriteLine(MyReader["title"].ToString());
                    user.Add(MyReader["id"].ToString());
                    user.Add(MyReader["name"].ToString());
                    user.Add(MyReader["surname"].ToString());
                    user.Add(MyReader["gender"].ToString());
                    user.Add(MyReader["age"].ToString());
                    user.Add(MyReader["email"].ToString());
                    user.Add(MyReader["password"].ToString());
                }

                conn.Close();

                parent parent = new parent();
                parent.id = Convert.ToInt32(user[0]);
                parent.name = user[1];
                parent.surname = user[2];
                parent.gender = user[3];
                parent.age = Convert.ToInt32(user[4]);
                parent.email = user[5];
                parent.password = user[6];
                return RedirectToAction("parent", parent);

            }
        }


        public ActionResult error()
        {
            return View();
        }
        [HttpPost]

        public ActionResult error(string str)
        {
            return View("Index");
        }


        public ActionResult student(student student)
        {

            List<student_main_page> p = new List<student_main_page>();
            //SELECT s.date,c.name,i.name FROM course_records cr left outer join section s on cr.sectionId = s.id left outer join course c on s.courseId=c.id left outer join instructor i on i.id=s.instructorId group BY cr.id ORDER BY cr.id;
            conn.Open();
            MySqlCommand cmd2 = new MySqlCommand($"SELECT s.date,c.name,i.name as names,i.surname,s.id FROM (select * from course_records cr1 where cr1.studentId={student.id}) cr left outer join section s on cr.sectionId = s.id left outer join course c on s.courseId=c.id left outer join instructor i on i.id=s.instructorId group BY cr.id ORDER BY cr.id;", conn);
            MySqlDataReader MyReader;
            MyReader = cmd2.ExecuteReader();
            while (MyReader.Read())
            {
                //Console.WriteLine(MyReader["title"].ToString());
                p.Add(new student_main_page() { section_date = MyReader["date"].ToString(), course_name = MyReader["name"].ToString(), instructor_name = MyReader["names"].ToString() + " " + MyReader["surname"].ToString(), section_id = Convert.ToInt32(MyReader["id"]) });
            }

            conn.Close();

            Ornek a = new Ornek();
            a.student = student;
            a.student_Main_Pages = p;
            return View(a);
        }
        //[HttpPost]
        //public ActionResult student(string str)
        //{
        //    return View();
        //}

        [AcceptVerbs(HttpVerbs.Get)]

        public ActionResult Signup()
        {

            return View();

        }


        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Signup(student user,HttpPostedFileBase image1)
        {
            //if (user.name == null || user.surname == null || user.email == null || user.password == null || user.gender == null || user.age==0) {
            //    return View("error");
            //}

            user.image = new byte[1]; 
            user.image[0] = 0x20;

            if (ModelState.IsValid == true)
            {
                conn.Open();
                MySqlCommand cmd = new MySqlCommand($"insert into student (name,surname,email,password,age,gender) values('{user.name}', '{user.surname}', '{user.email}', '{user.password}', '{user.age}', '{user.gender}');", conn);
                MySqlCommand cmd2 = new MySqlCommand($"insert into login(email,password,title) values( '{user.email}', '{user.password}', 'student');", conn);

course app/Views/Course/Index.cshtml
@model course_app.Models.login
@{

    ViewBag.Title = "Index";
}

<h1 style="color:indigo">WELCOME :) </h1>
<hr />
<h2>You must login or sign up to continue to website.</h2>



<div class="panel panel-info">
    <div class="panel-heading">
        <div class="panel-title">Sign In</div>
    </div>

    <div style="padding-top:30px" class="panel-body">

        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
        @using (Html.BeginForm("Login", "Course", FormMethod.Post, new { id = "empform" }))
        {
            <form id="loginform" class="form-horizontal" role="form">

                <div style="margin-bottom: 25px" class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    @*<input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username or email">*@

                    @Html.TextBoxFor(model => model.email, new { @class = "form-control", @placeholder = "username or email", @type = "email", required = "required" })
                </div>

                <div style="margin-bottom: 25px" class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    @*<input id="login-password" type="password" class="form-control" name="password" placeholder="password">*@
                    @Html.TextBoxFor(model => model.password, new { @class = "form-control", @placeholder = "password", @type = "password", required = "required" })
                </div>

                <div class="input-group">

                </div>


                <div style="margin-top:10px" class="form-group">
                    <!-- Button -->

                    <div class="col-sm-12 controls">
                        <button id="btn-login" href="#" class="btn btn-success" type="submit">Login  </button>

                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-12 control">
                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%">
                            Don't have an account!

                            @Html.ActionLink("Sign Up Here", "Signup", "Course", null)
                        </div>
                    </div>
                </div>
            </form>


        }
    </div>
</div>

course app/Views/Course/ViewSection.cshtml
@model course_app.Models.Ornek
@{
    ViewBag.Title = "ViewSection";
    int a = 0;
    if (Session["ActiveUser"] == null)
    {
        Response.Redirect("~/Course/Index");
    }
    else if (Session["ActiveUser"].ToString() != "registrar")
    {
        Response.Redirect("~/Course/Index");

    }

}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var id = @Html.Raw(Json.Encode(Model.registrar.id));
            $.ajax({

                url: '/Course/displayImage/' + id,
                data: { section: id },
                async: true,

                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $("#image").attr("src", "data:image/jpg;base64," + data);
                }

            });
        });
    </script>

</head>
@{ if (Model.registrar.name != null)
    {
        <body>
            <div class="container target">
                <div class="row">
                    <div class="col-sm-10">
                        <hr>
                        <h1 class="">@Html.ActionLink(Model.registrar.name.ToString() + " " + Model.registrar.surname.ToString(), "registrar", "Course", Model.registrar, new { @style = "text-decoration:none" })</h1>
                        <h2></h2>
                        @Html.ActionLink("New Teacher", "signTeacher", "Course", Model.registrar, new { @class = "btn btn-info" })
                        @Html.ActionLink("New Course", "createCourse", "Course", Model.registrar, new { @class = "btn btn-success" })
                        @Html.ActionLink("New Section", "addSection", "Course", Model.registrar, new { @class = "btn btn-info" })
                        @Html.ActionLink("Student List", "studentList", "Course", Model.registrar, new { @class = "btn btn-primary" })
                        @Html.ActionLink("New Parent", "signParent", "Course", Model.registrar, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Logout", "Index", "Course", null, new { @class = "btn btn-primary btn-danger" })

                        <br />
                    </div>
                    <div class="col-sm-2">
                        <a href="/users" class="pull-right"><img id="image" title="profile image" class="img-circle img-responsive" style="width:300px;max-height:200px" src=""></a>

                    </div>
                </div>
                <br>

                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Surname</th>
                            <th scope="col">Midterm</th>
                            <th scope="col">Final</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.students)
                        {


                        <tr>
                            @{a++;}
                            <th scope="row">@a</th>

                            <td>@Html.DisplayFor(modelItem => item.student_id)</td>
                            <td>@Html.DisplayFor(modelItem => item.student_name)</td>
                            <td>@Html.DisplayFor(modelItem => item.student_surname)</td>
                            @{ if (item.midterm < 0)
                                {
                                    <td></td>}
                                else
                                {
                                    <td>@Html.DisplayFor(modelItem => item.midterm)</td>}
                            }

                            @{ if (item.final < 0)
                                {
                                    <td></td>}
                                else
                                {
                                    <td>@Html.DisplayFor(modelItem => item.final)</td>}
                            }
                        </tr>

                        }

                    </tbody>
                </table>

            </div>
            <hr />
        </body>
    }
    else
    {
        <h3> Do you want to go to the mainpage?(If not you can go back to your page.)</h3>
        @Html.ActionLink("Main Page", "Index", "Course", null, new { @class = "btn btn-primary btn-danger" })
    }
}
</html>

course app/Views/Course/addChild.cshtml
@model course_app.Models.children

@{

    ViewBag.Title = "addChild";
    if (Session["ActiveUser"] == null)
    {
        Response.Redirect("~/Course/Index");
    }
    else if (Session["ActiveUser"].ToString() != "parent")
    {
        Response.Redirect("~/Course/Index");
    }
}

<div class="panel panel-info">
    <div class="panel-heading">
        <div class="panel-title">New Child</div>

    </div>
    <div class="panel-body">
        @using (Html.BeginForm("addchild", "Course", FormMethod.Post))
        {
            <form id="signupform" class="form-horizontal" role="form">

                <div id="signupalert" style="display:none" class="alert alert-danger">
                    <p>Error:</p>
                    <span></span>
                </div>


                <div class="form-group">
                    <label for="firstname" class="col-md-3 control-label">Please enter the Id of your child</label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(model=>model.student_id, new { @class = "form-control", @type = "number", @placeholder = "ID", required = "required" })
                    </div>
                </div>



                <div class="form-group">
                    <!-- Button -->
                    <div class="col-md-offset-3 col-md-9">
                        <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i> &nbsp Add Child</button>
                    </div>
                    @Html.ValidationSummary()
                </div>

            </form>
        }
    </div>
</div>

course app/Views/Course/addCourse.cshtml
@model course_app.Models.Ornek
@{
    ViewBag.Title = "addCourse";
    if (Session["ActiveUser"] == null)
    {
        Response.Redirect("~/Course/Index");
    }
    else if (Session["ActiveUser"].ToString() != "student")
    {
        Response.Redirect("~/Course/Index");
    }
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var id = @Html.Raw(Json.Encode(Model.student.id));
            $.ajax({

                url: '/Course/displayImage/' + id,
                data: { section: id },
                async: true,

                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $("#image").attr("src", "data:image/jpg;base64," + data);
                }

            });
        });
    </script>



</head>
@{
    if (Model.student.name != null)
    {
        <body>

            <hr class="">
            <div class="container target">
                <div class="row">
                    <div class="col-sm-10">

                        <h1 class="">@Html.ActionLink(Model.student.name.ToString() + " " + Model.student.surname.ToString(), "student", "Course", Model.student, new { @style = "text-decoration:none" })</h1>

                        @Html.ActionLink("Add Course", "addCourse", "Course", Model.student, new { @class = "btn btn-primary btn-success" })
                        @Html.ActionLink("Grades", "grades", "Course", Model.student, new { @class = "btn btn-primary btn-info" })

                        @Html.ActionLink("Logout", "Index", "Course", null, new { @class = "btn btn-primary btn-danger" })
                        <br>
                    </div>
                    <div class="col-sm-2">
                        <a href="/users" class="pull-right"><img id="image" title="profile image" class="img-circle img-responsive" style="width:300px;max-height:200px" src=""></a>

                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-3">
                        <!--left col-->
                        <ul class="list-group">
                            <li class="list-group-item text-muted" contenteditable="false">Profile</li>
                            <li class="list-group-item text-right"><span class="pull-left"><strong class="">ID  </strong></span> @Html.DisplayFor(model => model.student.id)</li>
                            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Name</strong></span> @Html.DisplayFor(model => model.student.name)</li>
                            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Surname</strong></span> @Html.DisplayFor(model => model.student.surname)</li>
                            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Age</strong></span> @Html.DisplayFor(model => model.student.age)</li>
                            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Mail </strong></span> @Html.DisplayFor(model => model.student.email) </li>
                            <li class="list-group-item text-right"><span class="pull-left"><strong class="">Gender </strong></span> @Html.DisplayFor(model => model.student.gender)</li>
                        </ul>


                    </div>
                    <!--/col-3-->
                    <div class="col-sm-9" style="" contenteditable="false">
                        <div class="panel panel-default">
                            <div class="panel-heading">Course List </div>
                            @foreach (var item in Model.student_Main_Pages)
                            {
                                <div class="panel-body">
                                    <h4>@Html.DisplayFor(modelItem => item.course_name)-Section:@Html.DisplayFor(modelItem => item.section_id)</h4>
                                    <ul>
                                        @{ Model.student.section_id = item.section_id;
                                        }
                                        @Html.ActionLink("Add", "add_button_student", "Course", Model.student, new { @class = "btn  btn-success pull-right" })

                                        <li>Date:@Html.DisplayFor(modelItem => item.section_date)</li>
                                        <li>Instructor:@Html.DisplayFor(modelItem => item.instructor_name) </li>
                                    </ul>
                                    <hr>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
            <hr />
        </body>
    }

    else
    {
        <h3> Do you want to go to the mainpage?(If not you can go back to your page.)</h3>
        @Html.ActionLink("Main Page", "Index", "Course", null, new { @class = "btn btn-primary btn-danger" })
    }
}
</html>

course app/Views/Course/addImage.cshtml
@model course_app.Models.student
@{
    ViewBag.Title = "addImage";
}

<h2>addImage</h2>
@using (Html.BeginForm("addImage", "Course", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    <form class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.image, new { @class = "control-label" })
            <div class="col-md-10">
                <input type="file" id="image1" name="image1" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                <button type="submit" value="submit" class="btn btn-success" />
            </div>
        </div>
    </form>
}

course app/Views/Course/retrieveImage.cshtml
@model course_app.Models.student
@{
    ViewBag.Title = "retrieveImage";
}

<h2>retrieveImage</h2>

    <table>
        <tr>
            
                <td>
                    @{


                        var base64 = Convert.ToBase64String(Model.image);
                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    }
                    <img src=@imgsrc style="max-width:100px;max-height:100px" />
                </td>
                        
        </tr>
    </table>
                        